### ISSUE TITLE
Why root-relative EPE is higher than absolute EPE (Table.1 in the paper) 

### ISSUE THREAD

**Issue by pyxploiter** [lixiny/POEM#5]
Hi,

Thanks for awesome work! I just have one confusion that I want to clear.

In Table.1 of your paper, you provide quantitative results (mm) of evaluations. I am confused why RR-V/RR-J are higher than MPVPE/MPJPE? As per my understanding, it should be like: PA-MPJPE < RR-MPJPE < absolute MPJPE. 

Thank you.

**Comment by lixiny** [comment]
Thank you for raising this issue,

We hypothesis that this behavior may closely related to the choice of the root joint. We have selected the 0-th point to align the vertices and joints. However, since the 0th joint is on the edge of the mesh model, using the coordinates of an edge point as the offset for the entire mesh model could potentially amplify the error.

I suggest experimenting with the 9-th joint (MCP joint) for root-relative MPJPE computation to see if the error decreases, which would help verify our hypothesis.

Best,

**Comment by pyxploiter** [comment]
The error does decrease if I select MCP point. Thanks for clarifying this
